SET IDENTITY_INSERT [dbo].[room] ON
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (11, N'Luxury Room Garden Non Lake View', N'Luxury Rooms offer princely-inspired décor with stunning views of the Lily Pond. Each room is unique in size and is adorned with traditional Indian silks and dark teak furniture.', N'21-33 Sq Mt                                       ', CAST(2 AS Decimal(1, 0)), N'King/Twin                                         ', CAST(37500 AS Decimal(18, 0)))
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (13, N'Luxury Room Lake View', N'Luxury Rooms have a princely-inspired décor with wooden lattice & araish work ceilings and discrete niches. They offer views of the placid waters of Lake Pichola. Each room is unique in size and is adorned with traditional Indian silks and dark teak furniture.', N'24-31 Sq Mt                                       ', CAST(2 AS Decimal(1, 0)), N'King/Twin                                         ', CAST(47500 AS Decimal(18, 0)))
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (14, N'Palace Room Lake View', N'Palace Rooms have a princely-inspired décor with wooden lattice & araish work ceilings and discrete niches. They offer views of the placid waters of Lake Pichola. Each room is unique in size and is adorned with traditional Indian silks and dark teak furniture.', N'28-42 Sq Mt                                       ', CAST(3 AS Decimal(1, 0)), N'King/Twin                                         ', CAST(52500 AS Decimal(18, 0)))
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (16, N'Historical 1 Bedroom Suite Lake View', N'The Historical Suites present a welcoming ambience with marble floors, exquisite Rajasthani artwork and sheer fabrics, which enable crisp sunlight to enhance the beauty of each room. A four-poster bed, a sitting area overlooking Lake Pichola, a walk-in wardrobe and a spacious bathroom make these suites ideal for the discerning leisure traveler. Suite Names are Rang Mahal, Sandhya & Sisarma Darshan.', N'42-61 Sq Mt                                       ', CAST(3 AS Decimal(1, 0)), N'King                                              ', CAST(64000 AS Decimal(18, 0)))
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (18, N'Grand Royal Suite 1 Bedroom Lake View', N'The Grand Royal Suites are the epitome of royal grandeur. Each of these individually themed suites feature high ceilings, deeply-carved mouldings, ornate glasswork, and miniature paintings. Many rooms offers unique features: Jacuzzi tubs, marble clad bathrooms with switch-lite glass windows, rain-showers, original works of art, crystal chandeliers.', N'74-108 Sq Mt                                      ', CAST(3 AS Decimal(1, 0)), N'
King                                            ', CAST(188400 AS Decimal(18, 0)))
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (20, N'Grand Presidential Suite 1 Bedroom Lake View', N'The Shambhu Prakash suite, named after the Maharana Shambhu Singh is remembered for his progressive reforms and welfare measures undertaken in the 1860s. This suite is furnished with high curved arches and has a European touch to its design. The adjoining balcony offers panoramic views of the lake and hills.', N'161 Sq Mt                                         ', CAST(4 AS Decimal(1, 0)), N'King                                              ', CAST(400000 AS Decimal(18, 0)))
INSERT INTO [dbo].[room] ([Id], [Type], [Desc], [area], [capasity], [bedtype], [price]) VALUES (23, N'Royal Suite 1 Bedroom Lake View', N'Outfitted in impeccable designs, each of the Royal Suites are adorned with stained glass windows offering stunning views of the lake and the Aravali mountain range. Suite Names are Basant Bahar, Machla Magra, Jag Mandir Darshan & Aravali Darshan. Basant Bahar and Jag Mandir Darshan are interconnected.', N'53-59 Sq Mt                                       ', CAST(3 AS Decimal(1, 0)), N' King                                             ', CAST(107600 AS Decimal(18, 0)))
SET IDENTITY_INSERT [dbo].[room] OFF
